# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9cfa334b72b26da5852d1859a4c484007a11b160eb5a889d1f7c87fb344d5cecdd857956d43870fd5866b111f7a5507c475889bed0e64311129bfdd188326d5

test:
  secret_key_base: 73e9c82b9dab69408b979e4267a01f29d8ea177fbb79ac3f038ff4c611e747a886ede249efe985482f3e99cdb004216e7977c3e50cc2b137e3432bf82f5c09a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
